// Date: 9/19/2013 11:00:58 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.mraof.minestuck.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelIguana extends ModelBase
{
  //fields
    ModelRenderer body;
    ModelRenderer RightLeg;
    ModelRenderer LeftLeg;
    ModelRenderer head;
    ModelRenderer UpperTail;
    ModelRenderer LowerTail;
    ModelRenderer UpperJaw;
    ModelRenderer LowerJaw;
    ModelRenderer Shape1;
    ModelRenderer Shape2;
  
  public ModelIguana()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      body = new ModelRenderer(this, 16, 16);
      body.addBox(-4F, 0F, -2F, 6, 8, 6);
      body.setRotationPoint(1F, 12F, -1F);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      RightLeg = new ModelRenderer(this, 0, 16);
      RightLeg.addBox(-2F, 0F, -2F, 2, 4, 3);
      RightLeg.setRotationPoint(-1F, 20F, 0F);
      RightLeg.mirror = true;
      setRotation(RightLeg, 0F, 0F, 0F);
      LeftLeg = new ModelRenderer(this, 0, 16);
      LeftLeg.addBox(-2F, 0F, -2F, 2, 4, 3);
      LeftLeg.setRotationPoint(3F, 20F, 0F);
      LeftLeg.mirror = true;
      setRotation(LeftLeg, 0F, 0F, 0F);
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-4F, -8F, -4F, 6, 4, 7);
      head.setRotationPoint(1F, 16F, 1F);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      UpperTail = new ModelRenderer(this, 0, 16);
      UpperTail.addBox(-2F, 0F, -2F, 2, 4, 2);
      UpperTail.setRotationPoint(1F, 18F, 4F);
      UpperTail.mirror = true;
      setRotation(UpperTail, 0.2230717F, 0F, 0F);
      LowerTail = new ModelRenderer(this, 0, 16);
      LowerTail.addBox(-2F, 0F, -2F, 2, 2, 6);
      LowerTail.setRotationPoint(1F, 22F, 5F);
      LowerTail.mirror = true;
      setRotation(LowerTail, 0F, 0F, 0F);
      UpperJaw = new ModelRenderer(this, 0, 0);
      UpperJaw.addBox(0F, 0F, 0F, 4, 1, 3);
      UpperJaw.setRotationPoint(-2F, 9F, -6F);
      UpperJaw.mirror = true;
      setRotation(UpperJaw, 0F, 0F, 0F);
      LowerJaw = new ModelRenderer(this, 48, 25);
      LowerJaw.addBox(0F, 0F, 0F, 4, 2, 3);
      LowerJaw.setRotationPoint(-2F, 10F, -6F);
      LowerJaw.mirror = true;
      setRotation(LowerJaw, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 1, 1, 1);
      Shape1.setRotationPoint(-0.6F, 10.5F, 4F);
      Shape1.mirror = true;
      setRotation(Shape1, -0.9294653F, 0F, 0F);
      Shape1.mirror = true;
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 1, 2, 2);
      Shape1.setRotationPoint(-0.6F, 8F, 4F);
      Shape1.mirror = true;
      setRotation(Shape1, -0.8179294F, 0F, 0F);
      Shape1.mirror = false;
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    body.render(f5);
    RightLeg.render(f5);
    LeftLeg.render(f5);
    head.render(f5);
    UpperTail.render(f5);
    LowerTail.render(f5);
    UpperJaw.render(f5);
    LowerJaw.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
