// Date: 12/8/2016 3:20:33 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.mraof.minestuck.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelTurtle extends ModelBase
{
	ModelRenderer head;
	ModelRenderer leg1;
	ModelRenderer leg2;
	ModelRenderer tail;
	ModelRenderer body;
	ModelRenderer shell;
	ModelRenderer shellRim;
	ModelRenderer nose;
	
	public ModelTurtle()
	{
		textureWidth = 64;
		textureHeight = 128;
		
		head = new ModelRenderer(this, 0, 0);
		head.addBox(-4F, -4F, -6F, 8, 8, 10);
		head.setRotationPoint(0F, 1F, 0F);
		head.setTextureSize(64, 128);
		head.mirror = true;
		setRotation(head, 0F, 0F, 0F);
		leg1 = new ModelRenderer(this, 31, 0);
		leg1.addBox(-1F, 0F, -2F, 4, 6, 4);
		leg1.setRotationPoint(2F, 18F, 1F);
		leg1.setTextureSize(64, 128);
		leg1.mirror = true;
		setRotation(leg1, 0F, 0F, 0F);
		leg2 = new ModelRenderer(this, 31, 0);
		leg2.addBox(-1F, 0F, -2F, 4, 6, 4);
		leg2.setRotationPoint(-4F, 18F, 1F);
		leg2.setTextureSize(64, 128);
		leg2.mirror = true;
		setRotation(leg2, 0F, 0F, 0F);
		tail = new ModelRenderer(this, 31, 0);
		tail.addBox(-2F, -3F, -1F, 4, 7, 2);
		tail.setRotationPoint(0F, 19F, 4F);
		tail.setTextureSize(64, 128);
		tail.mirror = true;
		setRotation(tail, 0.2974289F, 0F, 0F);
		body = new ModelRenderer(this, 0, 52);
		body.addBox(-5F, -3F, -6F, 10, 7, 13);
		body.setRotationPoint(0F, 12F, 0F);
		body.setTextureSize(64, 128);
		body.mirror = true;
		setRotation(body, 1.570796F, 0F, 0F);
		shell = new ModelRenderer(this, 0, 18);
		shell.addBox(-4F, 0F, -4F, 10, 3, 13);
		shell.setRotationPoint(-1F, 14F, 5F);
		shell.setTextureSize(64, 128);
		shell.mirror = true;
		setRotation(shell, 1.570796F, 0F, 0F);
		shellRim = new ModelRenderer(this, 0, 34);
		shellRim.addBox(-5F, -1F, -7F, 12, 1, 15);
		shellRim.setRotationPoint(-1F, 12F, 5F);
		shellRim.setTextureSize(64, 128);
		shellRim.mirror = true;
		setRotation(shellRim, 1.570796F, 0F, 0F);
		nose = new ModelRenderer(this, 31, 1);
		nose.addBox(-4F, -4F, -2F, 6, 5, 3);
		nose.setRotationPoint(1F, 3F, -7F);
		nose.setTextureSize(64, 128);
		nose.mirror = true;
		setRotation(nose, 0F, 0F, 0F);
	}
	
	@Override
	public void render(Entity entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scale)
	{
		super.render(entity, limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch, scale);
		setRotationAngles(limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch, scale, entity);
		head.render(scale);
		leg1.render(scale);
		leg2.render(scale);
		tail.render(scale);
		body.render(scale);
		shell.render(scale);
		shellRim.render(scale);
		nose.render(scale);
	}
	
	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
}